### ISSUE TITLE
eval_rcnn.py RuntimeError: shape mismatch

### ISSUE THREAD

**Issue by honglongcai** [sshaoshuai/PointRCNN#106]
2019-09-13 11:27:40,282   INFO  **********************Start logging**********************
2019-09-13 11:27:40,283   INFO  cfg_file         cfgs/default.yaml
2019-09-13 11:27:40,283   INFO  eval_mode        rcnn
2019-09-13 11:27:40,283   INFO  eval_all         False
2019-09-13 11:27:40,283   INFO  test             False
2019-09-13 11:27:40,283   INFO  ckpt             ../models/PointRCNN.pth
2019-09-13 11:27:40,283   INFO  rpn_ckpt         None
2019-09-13 11:27:40,283   INFO  rcnn_ckpt        None
2019-09-13 11:27:40,283   INFO  batch_size       1
2019-09-13 11:27:40,283   INFO  workers          4
2019-09-13 11:27:40,283   INFO  extra_tag        default
2019-09-13 11:27:40,283   INFO  output_dir       None
2019-09-13 11:27:40,283   INFO  ckpt_dir         None
2019-09-13 11:27:40,283   INFO  save_result      False
2019-09-13 11:27:40,283   INFO  save_rpn_feature False
2019-09-13 11:27:40,283   INFO  random_select    True
2019-09-13 11:27:40,283   INFO  start_epoch      0
2019-09-13 11:27:40,284   INFO  rcnn_eval_roi_dir None
2019-09-13 11:27:40,284   INFO  rcnn_eval_feature_dir None
2019-09-13 11:27:40,284   INFO  set_cfgs         ['RPN.LOC_XZ_FINE', 'False']
2019-09-13 11:27:40,284   INFO  cfg.TAG: default
2019-09-13 11:27:40,284   INFO  cfg.CLASSES: Car
2019-09-13 11:27:40,284   INFO  cfg.INCLUDE_SIMILAR_TYPE: True
2019-09-13 11:27:40,284   INFO  cfg.AUG_DATA: True
2019-09-13 11:27:40,284   INFO  cfg.AUG_METHOD_LIST: ['rotation', 'scaling', 'flip']
2019-09-13 11:27:40,284   INFO  cfg.AUG_METHOD_PROB: [1.0, 1.0, 0.5]
2019-09-13 11:27:40,284   INFO  cfg.AUG_ROT_RANGE: 18
2019-09-13 11:27:40,284   INFO  cfg.GT_AUG_ENABLED: True
2019-09-13 11:27:40,284   INFO  cfg.GT_EXTRA_NUM: 15
2019-09-13 11:27:40,284   INFO  cfg.GT_AUG_RAND_NUM: True
2019-09-13 11:27:40,284   INFO  cfg.GT_AUG_APPLY_PROB: 1.0
2019-09-13 11:27:40,284   INFO  cfg.GT_AUG_HARD_RATIO: 0.6
2019-09-13 11:27:40,284   INFO  cfg.PC_REDUCE_BY_RANGE: True
2019-09-13 11:27:40,285   INFO  cfg.PC_AREA_SCOPE: [[-40.   40. ]
 [ -1.    3. ]
 [  0.   70.4]]
2019-09-13 11:27:40,285   INFO  cfg.CLS_MEAN_SIZE: [[1.5256319 1.6285675 3.8831165]]
2019-09-13 11:27:40,285   INFO  
cfg.RPN = edict()
2019-09-13 11:27:40,285   INFO  cfg.RPN.ENABLED: True
2019-09-13 11:27:40,285   INFO  cfg.RPN.FIXED: True
2019-09-13 11:27:40,285   INFO  cfg.RPN.USE_INTENSITY: False
2019-09-13 11:27:40,285   INFO  cfg.RPN.LOC_XZ_FINE: False
2019-09-13 11:27:40,285   INFO  cfg.RPN.LOC_SCOPE: 3.0
2019-09-13 11:27:40,285   INFO  cfg.RPN.LOC_BIN_SIZE: 0.5
2019-09-13 11:27:40,285   INFO  cfg.RPN.NUM_HEAD_BIN: 12
2019-09-13 11:27:40,285   INFO  cfg.RPN.BACKBONE: pointnet2_msg
2019-09-13 11:27:40,285   INFO  cfg.RPN.USE_BN: True
2019-09-13 11:27:40,285   INFO  cfg.RPN.NUM_POINTS: 16384
2019-09-13 11:27:40,285   INFO  
cfg.RPN.SA_CONFIG = edict()
2019-09-13 11:27:40,285   INFO  cfg.RPN.SA_CONFIG.NPOINTS: [4096, 1024, 256, 64]
2019-09-13 11:27:40,285   INFO  cfg.RPN.SA_CONFIG.RADIUS: [[0.1, 0.5], [0.5, 1.0], [1.0, 2.0], [2.0, 4.0]]
2019-09-13 11:27:40,286   INFO  cfg.RPN.SA_CONFIG.NSAMPLE: [[16, 32], [16, 32], [16, 32], [16, 32]]
2019-09-13 11:27:40,286   INFO  cfg.RPN.SA_CONFIG.MLPS: [[[16, 16, 32], [32, 32, 64]], [[64, 64, 128], [64, 96, 128]], [[128, 196, 256], [128, 196, 256]], [[256, 256, 512], [256, 384, 512]]]
2019-09-13 11:27:40,286   INFO  cfg.RPN.FP_MLPS: [[128, 128], [256, 256], [512, 512], [512, 512]]
2019-09-13 11:27:40,286   INFO  cfg.RPN.CLS_FC: [128]
2019-09-13 11:27:40,286   INFO  cfg.RPN.REG_FC: [128]
2019-09-13 11:27:40,286   INFO  cfg.RPN.DP_RATIO: 0.5
2019-09-13 11:27:40,286   INFO  cfg.RPN.LOSS_CLS: SigmoidFocalLoss
2019-09-13 11:27:40,286   INFO  cfg.RPN.FG_WEIGHT: 15
2019-09-13 11:27:40,286   INFO  cfg.RPN.FOCAL_ALPHA: [0.25, 0.75]
2019-09-13 11:27:40,286   INFO  cfg.RPN.FOCAL_GAMMA: 2.0
2019-09-13 11:27:40,286   INFO  cfg.RPN.REG_LOSS_WEIGHT: [1.0, 1.0, 1.0, 1.0]
2019-09-13 11:27:40,286   INFO  cfg.RPN.LOSS_WEIGHT: [1.0, 1.0]
2019-09-13 11:27:40,286   INFO  cfg.RPN.NMS_TYPE: normal
2019-09-13 11:27:40,286   INFO  cfg.RPN.SCORE_THRESH: 0.3
2019-09-13 11:27:40,286   INFO  
cfg.RCNN = edict()
2019-09-13 11:27:40,286   INFO  cfg.RCNN.ENABLED: True
2019-09-13 11:27:40,286   INFO  cfg.RCNN.USE_RPN_FEATURES: True
2019-09-13 11:27:40,286   INFO  cfg.RCNN.USE_MASK: True
2019-09-13 11:27:40,286   INFO  cfg.RCNN.MASK_TYPE: seg
2019-09-13 11:27:40,286   INFO  cfg.RCNN.USE_INTENSITY: False
2019-09-13 11:27:40,287   INFO  cfg.RCNN.USE_DEPTH: True
2019-09-13 11:27:40,287   INFO  cfg.RCNN.USE_SEG_SCORE: False
2019-09-13 11:27:40,287   INFO  cfg.RCNN.ROI_SAMPLE_JIT: True
2019-09-13 11:27:40,287   INFO  cfg.RCNN.ROI_FG_AUG_TIMES: 10
2019-09-13 11:27:40,287   INFO  cfg.RCNN.REG_AUG_METHOD: multiple
2019-09-13 11:27:40,287   INFO  cfg.RCNN.POOL_EXTRA_WIDTH: 1.0
2019-09-13 11:27:40,287   INFO  cfg.RCNN.LOC_SCOPE: 1.5
2019-09-13 11:27:40,287   INFO  cfg.RCNN.LOC_BIN_SIZE: 0.5
2019-09-13 11:27:40,287   INFO  cfg.RCNN.NUM_HEAD_BIN: 9
2019-09-13 11:27:40,287   INFO  cfg.RCNN.LOC_Y_BY_BIN: False
2019-09-13 11:27:40,287   INFO  cfg.RCNN.LOC_Y_SCOPE: 0.5
2019-09-13 11:27:40,287   INFO  cfg.RCNN.LOC_Y_BIN_SIZE: 0.25
2019-09-13 11:27:40,287   INFO  cfg.RCNN.SIZE_RES_ON_ROI: False
2019-09-13 11:27:40,287   INFO  cfg.RCNN.USE_BN: False
2019-09-13 11:27:40,287   INFO  cfg.RCNN.DP_RATIO: 0.0
2019-09-13 11:27:40,287   INFO  cfg.RCNN.BACKBONE: pointnet
2019-09-13 11:27:40,287   INFO  cfg.RCNN.XYZ_UP_LAYER: [128, 128]
2019-09-13 11:27:40,287   INFO  cfg.RCNN.NUM_POINTS: 512
2019-09-13 11:27:40,287   INFO  
cfg.RCNN.SA_CONFIG = edict()
2019-09-13 11:27:40,287   INFO  cfg.RCNN.SA_CONFIG.NPOINTS: [128, 32, -1]
2019-09-13 11:27:40,288   INFO  cfg.RCNN.SA_CONFIG.RADIUS: [0.2, 0.4, 100]
2019-09-13 11:27:40,288   INFO  cfg.RCNN.SA_CONFIG.NSAMPLE: [64, 64, 64]
2019-09-13 11:27:40,288   INFO  cfg.RCNN.SA_CONFIG.MLPS: [[128, 128, 128], [128, 128, 256], [256, 256, 512]]
2019-09-13 11:27:40,288   INFO  cfg.RCNN.CLS_FC: [256, 256]
2019-09-13 11:27:40,288   INFO  cfg.RCNN.REG_FC: [256, 256]
2019-09-13 11:27:40,288   INFO  cfg.RCNN.LOSS_CLS: BinaryCrossEntropy
2019-09-13 11:27:40,288   INFO  cfg.RCNN.FOCAL_ALPHA: [0.25, 0.75]
2019-09-13 11:27:40,288   INFO  cfg.RCNN.FOCAL_GAMMA: 2.0
2019-09-13 11:27:40,288   INFO  cfg.RCNN.CLS_WEIGHT: [1. 1. 1.]
2019-09-13 11:27:40,288   INFO  cfg.RCNN.CLS_FG_THRESH: 0.6
2019-09-13 11:27:40,288   INFO  cfg.RCNN.CLS_BG_THRESH: 0.45
2019-09-13 11:27:40,288   INFO  cfg.RCNN.CLS_BG_THRESH_LO: 0.05
2019-09-13 11:27:40,288   INFO  cfg.RCNN.REG_FG_THRESH: 0.55
2019-09-13 11:27:40,288   INFO  cfg.RCNN.FG_RATIO: 0.5
2019-09-13 11:27:40,288   INFO  cfg.RCNN.ROI_PER_IMAGE: 64
2019-09-13 11:27:40,288   INFO  cfg.RCNN.HARD_BG_RATIO: 0.8
2019-09-13 11:27:40,288   INFO  cfg.RCNN.SCORE_THRESH: 0.3
2019-09-13 11:27:40,289   INFO  cfg.RCNN.NMS_THRESH: 0.1
2019-09-13 11:27:40,289   INFO  
cfg.TRAIN = edict()
2019-09-13 11:27:40,289   INFO  cfg.TRAIN.SPLIT: train
2019-09-13 11:27:40,289   INFO  cfg.TRAIN.VAL_SPLIT: smallval
2019-09-13 11:27:40,289   INFO  cfg.TRAIN.LR: 0.002
2019-09-13 11:27:40,289   INFO  cfg.TRAIN.LR_CLIP: 1e-05
2019-09-13 11:27:40,289   INFO  cfg.TRAIN.LR_DECAY: 0.5
2019-09-13 11:27:40,289   INFO  cfg.TRAIN.DECAY_STEP_LIST: [100, 150, 180, 200]
2019-09-13 11:27:40,289   INFO  cfg.TRAIN.LR_WARMUP: True
2019-09-13 11:27:40,289   INFO  cfg.TRAIN.WARMUP_MIN: 0.0002
2019-09-13 11:27:40,289   INFO  cfg.TRAIN.WARMUP_EPOCH: 1
2019-09-13 11:27:40,289   INFO  cfg.TRAIN.BN_MOMENTUM: 0.1
2019-09-13 11:27:40,289   INFO  cfg.TRAIN.BN_DECAY: 0.5
2019-09-13 11:27:40,289   INFO  cfg.TRAIN.BNM_CLIP: 0.01
2019-09-13 11:27:40,289   INFO  cfg.TRAIN.BN_DECAY_STEP_LIST: [1000]
2019-09-13 11:27:40,289   INFO  cfg.TRAIN.OPTIMIZER: adam_onecycle
2019-09-13 11:27:40,289   INFO  cfg.TRAIN.WEIGHT_DECAY: 0.001
2019-09-13 11:27:40,289   INFO  cfg.TRAIN.MOMENTUM: 0.9
2019-09-13 11:27:40,289   INFO  cfg.TRAIN.MOMS: [0.95, 0.85]
2019-09-13 11:27:40,289   INFO  cfg.TRAIN.DIV_FACTOR: 10.0
2019-09-13 11:27:40,290   INFO  cfg.TRAIN.PCT_START: 0.4
2019-09-13 11:27:40,290   INFO  cfg.TRAIN.GRAD_NORM_CLIP: 1.0
2019-09-13 11:27:40,290   INFO  cfg.TRAIN.RPN_PRE_NMS_TOP_N: 9000
2019-09-13 11:27:40,290   INFO  cfg.TRAIN.RPN_POST_NMS_TOP_N: 512
2019-09-13 11:27:40,290   INFO  cfg.TRAIN.RPN_NMS_THRESH: 0.85
2019-09-13 11:27:40,290   INFO  cfg.TRAIN.RPN_DISTANCE_BASED_PROPOSE: True
2019-09-13 11:27:40,290   INFO  
cfg.TEST = edict()
2019-09-13 11:27:40,290   INFO  cfg.TEST.SPLIT: val
2019-09-13 11:27:40,290   INFO  cfg.TEST.RPN_PRE_NMS_TOP_N: 9000
2019-09-13 11:27:40,290   INFO  cfg.TEST.RPN_POST_NMS_TOP_N: 100
2019-09-13 11:27:40,290   INFO  cfg.TEST.RPN_NMS_THRESH: 0.8
2019-09-13 11:27:40,290   INFO  cfg.TEST.RPN_DISTANCE_BASED_PROPOSE: True
2019-09-13 11:27:40,292   INFO  Load testing samples from ../data/KITTI/object/training
2019-09-13 11:27:40,292   INFO  Done: total test samples 3769
2019-09-13 11:27:43,336   INFO  ==> Loading from checkpoint '../models/PointRCNN.pth'
2019-09-13 11:27:43,413   INFO  ==> Done
2019-09-13 11:27:43,414   INFO  ---- EPOCH no_number JOINT EVALUATION ----
2019-09-13 11:27:43,414   INFO  ==> Output file: ../output/rcnn/default/eval/epoch_no_number/val
eval:  48%|▍| 1827/3769 [06:46<25:41,  1.26it/s, mode=EVAL, recall=1441151880800eval:  49%|▍| 1828/3769 [06:46<4:45:46,  8.83s/it, mode=EVAL, recall=144115188080092746/6871]Traceback (most recent call last):
  File "eval_rcnn.py", line 902, in <module>
    eval_single_ckpt(root_result_dir)
  File "eval_rcnn.py", line 765, in eval_single_ckpt
    eval_one_epoch(model, test_loader, epoch_id, root_result_dir, logger)
  File "eval_rcnn.py", line 692, in eval_one_epoch
    ret_dict = eval_one_epoch_joint(model, dataloader, epoch_id, result_dir, logger)
  File "eval_rcnn.py", line 495, in eval_one_epoch_joint
    ret_dict = model(input_data)
  File "/home/honglongcai/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/honglongcai/Github/PointRCNN/tools/../lib/net/point_rcnn.py", line 48, in forward
    rois, roi_scores_raw = self.rpn.proposal_layer(rpn_scores_raw, rpn_reg, backbone_xyz)  # (B, M, 7)
  File "/home/honglongcai/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/honglongcai/Github/PointRCNN/tools/../lib/rpn/proposal_layer.py", line 30, in forward
    get_ry_fine=False)  # (N, 7)
  File "/home/honglongcai/Github/PointRCNN/tools/../lib/utils/bbox_transform.py", line 102, in decode_bbox_target
    ry[ry > np.pi] -= 2 * np.pi
RuntimeError: shape mismatch: value tensor of shape [4231196] cannot be broadcast to indexing result of shape [334]
eval:  49%|▍| 1828/3769 [06:54<07:20,  4.41it/s, mode=EVAL, recall=144115188080092746/6871]

**Comment by onecodeonehair** [comment]
did you solved it,i have the same question
