### ISSUE TITLE
how to test on test_datasets without ground truth?

### ISSUE THREAD

**Issue by Yxiaoqian** [sshaoshuai/PointRCNN#122]

**Comment by Yxiaoqian** [comment]
python eval_rcnn.py --cfg_file cfgs/default.yaml --eval_mode rcnn --test --start_epoch 70
but I get the error:
numba.cuda.cudadrv.driver.CudaAPIError: [999] Call to cuDevicePrimaryCtxRetain results in CUDA_ERROR_UNKNOWN

**Comment by lyuweiwang** [comment]
same issue when I run "python eval_rcnn.py --cfg_file cfgs/default.yaml --ckpt PointRCNN.pth --batch_size 1 --eval_mode rcnn --set RPN.LOC_XZ_FINE False". Whole traceback is:
Traceback (most recent call last):
  File "eval_rcnn.py", line 11, in <module>
    from tools.kitti_object_eval_python.evaluate import evaluate as kitti_evaluate
  File "/home/luban/PointRCNN/tools/../tools/kitti_object_eval_python/evaluate.py", line 5, in <module>
    from tools.kitti_object_eval_python.eval import get_official_eval_result, get_coco_eval_result
  File "/home/luban/PointRCNN/tools/../tools/kitti_object_eval_python/eval.py", line 4, in <module>
    from tools.kitti_object_eval_python.rotate_iou import rotate_iou_gpu_eval
  File "/home/luban/PointRCNN/tools/../tools/kitti_object_eval_python/rotate_iou.py", line 262, in <module>
    def rotate_iou_kernel_eval(N, K, dev_boxes, dev_query_boxes, dev_iou, criterion=-1):
  File "/home/luban/miniconda3/lib/python3.7/site-packages/numba/cuda/decorators.py", line 98, in kernel_jit
    kernel.bind()
  File "/home/luban/miniconda3/lib/python3.7/site-packages/numba/cuda/compiler.py", line 543, in bind
    self._func.get()
  File "/home/luban/miniconda3/lib/python3.7/site-packages/numba/cuda/compiler.py", line 417, in get
    cuctx = get_context()
  File "/home/luban/miniconda3/lib/python3.7/site-packages/numba/cuda/cudadrv/devices.py", line 213, in get_context
    return _runtime.get_or_create_context(devnum)
  File "/home/luban/miniconda3/lib/python3.7/site-packages/numba/cuda/cudadrv/devices.py", line 139, in get_or_create_context
    return self._get_or_create_context_uncached(devnum)
  File "/home/luban/miniconda3/lib/python3.7/site-packages/numba/cuda/cudadrv/devices.py", line 154, in _get_or_create_context_uncached
    return self._activate_context_for(0)
  File "/home/luban/miniconda3/lib/python3.7/site-packages/numba/cuda/cudadrv/devices.py", line 170, in _activate_context_for
    newctx = gpu.get_primary_context()
  File "/home/luban/miniconda3/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 528, in get_primary_context
    driver.cuDevicePrimaryCtxRetain(byref(hctx), self.id)
  File "/home/luban/miniconda3/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 294, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/luban/miniconda3/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 329, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [999] Call to cuDevicePrimaryCtxRetain results in CUDA_ERROR_UNKNOWN

**Comment by lyuweiwang** [comment]
maybe a simple restart will solve your problem

**Comment by supercpy** [comment]
@yxxxqqq ,so how to solve this problem? Thanks!

> python eval_rcnn.py --cfg_file cfgs/default.yaml --eval_mode rcnn --test --start_epoch 70
> but I get the error:
> numba.cuda.cudadrv.driver.CudaAPIError: [999] Call to cuDevicePrimaryCtxRetain results in CUDA_ERROR_UNKNOWN

**Comment by direcf** [comment]
Hi, I solve this problem for changing TEST SPLIT : from 'val' to 'test' in default.yaml file
If you don't solve this problem, please ask me one more time
Thx
