### ISSUE TITLE
RCNN.ROI_SAMPLE_JIT = False does not works.

### ISSUE THREAD

**Issue by fukatani** [sshaoshuai/PointRCNN#123]
Traceback is here.

I tried
```
train_rcnn.py --cfg_file cfgs/default.yaml --batch_size 4 --train_mode rcnn --epochs 70  --ckpt_save_interval 2 --rpn_ckpt ../output/rpn/default3/ckpt/checkpoint_epoch_200.pth --gt_database ./gt_database/train_gt_database_3level_Car.pkl;
```
with modifying default.yml that `RCNN.ROI_SAMPLE = False`.
Since the author say the best parameter .

But It does not work for me.
```
Traceback (most recent call last):                                                                                                                                                                                      
  File "train_rcnn.py", line 250, in <module>
    lr_scheduler_each_iter=(cfg.TRAIN.OPTIMIZER == 'adam_onecycle')
  File "/home/briv/PointRCNN/tools/../tools/train_utils/train_utils.py", line 199, in train
    loss, tb_dict, disp_dict = self._train_it(batch)
  File "/home/briv/PointRCNN/tools/../tools/train_utils/train_utils.py", line 132, in _train_it
    loss, tb_dict, disp_dict = self.model_fn(self.model, batch)
  File "/home/briv/PointRCNN/tools/../lib/net/train_functions.py", line 35, in model_fn
    ret_dict = model(input_data)
  File "/home/briv/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/briv/PointRCNN/tools/../lib/net/point_rcnn.py", line 62, in forward
    rcnn_output = self.rcnn_net(rcnn_input_info)
  File "/home/briv/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/briv/PointRCNN/tools/../lib/net/rcnn_net.py", line 156, in forward
    pts_input = input_data['pts_input']
KeyError: 'pts_input'
```

Did anyone succeed to train rcnn with `RCNN.ROI_SAMPLE_JIT = False`?

**Comment by gigadeplex** [comment]
solved this?

**Comment by fukatani** [comment]
I found ` --train_mode rcnn_offline` is needed. Please see Train RCNN stage (b).
