### ISSUE TITLE
ModuleNotFoundError: No module named 'iou3d_cuda'

### ISSUE THREAD

**Issue by gggg231** [sshaoshuai/PointRCNN#137]
Quick demo
python eval_rcnn.py --cfg_file cfgs/default.yaml --ckpt PointRCNN.pth --batch_size 1 --eval_mode rcnn --set RPN.LOC_XZ_FINE False

=>

Traceback (most recent call last):
  File "eval_rcnn.py", line 7, in <module>
    from lib.net.point_rcnn import PointRCNN
  File "/home/iris/PointRCNN/tools/../lib/net/point_rcnn.py", line 3, in <module>
    from lib.net.rpn import RPN
  File "/home/iris/PointRCNN/tools/../lib/net/rpn.py", line 4, in <module>
    from lib.rpn.proposal_layer import ProposalLayer
  File "/home/iris/PointRCNN/tools/../lib/rpn/proposal_layer.py", line 6, in <module>
    import lib.utils.iou3d.iou3d_utils as iou3d_utils
  File "/home/iris/PointRCNN/tools/../lib/utils/iou3d/iou3d_utils.py", line 2, in <module>
    import iou3d_cuda
ModuleNotFoundError: No module named 'iou3d_cuda'

**Comment by seboz123** [comment]
You have to run the build_and_install.sh script beforehand!

**Comment by gehadza** [comment]
How to run build_and_install.sh script in windows

**Comment by Hyperjunct** [comment]
> How to run build_and_install.sh script in windows

Have you handle this problem?
