### ISSUE TITLE
Assert Problem!

### ISSUE THREAD

**Issue by yinhai86924** [sshaoshuai/PointRCNN#143]
eval:   0%|          | 0/3769 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/yin/PointRCNN/tools/eval_rcnn.py", line 902, in <module>
    eval_single_ckpt(root_result_dir)
  File "/home/yin/PointRCNN/tools/eval_rcnn.py", line 765, in eval_single_ckpt
    eval_one_epoch(model, test_loader, epoch_id, root_result_dir, logger)
  File "/home/yin/PointRCNN/tools/eval_rcnn.py", line 692, in eval_one_epoch
    ret_dict = eval_one_epoch_joint(model, dataloader, epoch_id, result_dir, logger)
  File "/home/yin/PointRCNN/tools/eval_rcnn.py", line 486, in eval_one_epoch_joint
    for data in dataloader:
  File "/home/yin/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/yin/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AssertionError: Traceback (most recent call last):
  File "/home/yin/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/yin/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/yin/PointRCNN/tools/../lib/datasets/kitti_rcnn_dataset.py", line 234, in __getitem__
    return self.get_rpn_sample(index)
  File "/home/yin/PointRCNN/tools/../lib/datasets/kitti_rcnn_dataset.py", line 249, in get_rpn_sample
    calib = self.get_calib(sample_id)
  File "/home/yin/PointRCNN/tools/../lib/datasets/kitti_rcnn_dataset.py", line 133, in get_calib
    return super().get_calib(idx % 10000)
  File "/home/yin/PointRCNN/tools/../lib/datasets/kitti_dataset.py", line 47, in get_calib
    assert os.path.exists(calib_file)
AssertionError

**Comment by killernic123** [comment]
Yes, even i got the same problem. How to resolve it?

**Comment by Stone-sy** [comment]
请问如何解决？

**Comment by Liaoqing-up** [comment]
I also have this problem, have you resolved it? Can you give me some help? Thanks!

**Comment by paulchze** [comment]
me too!Can you give me some help?

**Comment by paulchze** [comment]
I find the problem which is because of the wrong of the file path

**Comment by VbsmRobotic** [comment]
Hello everyone,

I'm encountering the same error. Is there a solution available for this issue? If it turns out to be related to an incorrect file path, can be created a variable for it in cfgs/default.yaml?

![kitti_dataset_ImageSets](https://github.com/sshaoshuai/PointRCNN/assets/63047516/2bb5d626-22b1-4ed7-98fd-84ad62062961)
Why need imageSets?

**Comment by Stone-sy** [comment]
您好！您的邮件我已收到！

**Comment by kingyongyongzz** [comment]
您好作者，我想问下我也出现了这个问题，但是我的数据集路径应该没错，为什么还是报这个错呢？eval:   0%|                                                                                                                                 | 0/3769 [00:00<?, ?it/s]Traceback (most recent call last):
  File "eval_rcnn.py", line 902, in <module>
    eval_single_ckpt(root_result_dir)
  File "eval_rcnn.py", line 765, in eval_single_ckpt
    eval_one_epoch(model, test_loader, epoch_id, root_result_dir, logger)
  File "eval_rcnn.py", line 692, in eval_one_epoch
    ret_dict = eval_one_epoch_joint(model, dataloader, epoch_id, result_dir, logger)
  File "eval_rcnn.py", line 486, in eval_one_epoch_joint
    for data in dataloader:
  File "/home/wzy/anaconda3/envs/torch1.0/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/wzy/anaconda3/envs/torch1.0/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/wzy/anaconda3/envs/torch1.0/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/wzy/anaconda3/envs/torch1.0/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/wzy/anaconda3/envs/torch1.0/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/wzy/anaconda3/envs/torch1.0/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/wzy/anaconda3/envs/torch1.0/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/wzy/PointRCNN/tools/../lib/datasets/kitti_rcnn_dataset.py", line 234, in __getitem__
    return self.get_rpn_sample(index)
  File "/home/wzy/PointRCNN/tools/../lib/datasets/kitti_rcnn_dataset.py", line 251, in get_rpn_sample
    img_shape = self.get_image_shape(sample_id)
  File "/home/wzy/PointRCNN/tools/../lib/datasets/kitti_rcnn_dataset.py", line 130, in get_image_shape
    return super().get_image_shape(idx % 10000)
  File "/home/wzy/PointRCNN/tools/../lib/datasets/kitti_dataset.py", line 35, in get_image_shape
    assert os.path.exists(img_file)
AssertionError
![图片](https://github.com/user-attachments/assets/48b40842-0f2b-4abb-bf7a-b5b0cf847c6b)
