### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by 1992Zz** [sshaoshuai/PointRCNN#176]
sh build_and_install.sh 
prompt：
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    cmdclass={'build_ext': BuildExtension})
  File "/home/helloworld/miniconda3/envs/py36/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/helloworld/miniconda3/envs/py36/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/helloworld/miniconda3/envs/py36/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/helloworld/miniconda3/envs/py36/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/helloworld/miniconda3/envs/py36/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/helloworld/miniconda3/envs/py36/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/helloworld/miniconda3/envs/py36/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/helloworld/miniconda3/envs/py36/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 169, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/helloworld/miniconda3/envs/py36/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 155, in call_command
    self.run_command(cmdname)
  File "/home/helloworld/miniconda3/envs/py36/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/helloworld/miniconda3/envs/py36/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/helloworld/miniconda3/envs/py36/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/helloworld/miniconda3/envs/py36/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/helloworld/miniconda3/envs/py36/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/helloworld/miniconda3/envs/py36/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/helloworld/miniconda3/envs/py36/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 75, in run
    _build_ext.run(self)
  File "/home/helloworld/miniconda3/envs/py36/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/helloworld/miniconda3/envs/py36/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 580, in build_extensions
    build_ext.build_extensions(self)
  File "/home/helloworld/miniconda3/envs/py36/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/helloworld/miniconda3/envs/py36/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/helloworld/miniconda3/envs/py36/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/helloworld/miniconda3/envs/py36/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/helloworld/miniconda3/envs/py36/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 423, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/helloworld/miniconda3/envs/py36/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/helloworld/miniconda3/envs/py36/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

**Comment by 1992Zz** [comment]
I already solve the problem and it's because that my Pytorch verison is 1.50.

**Comment by daxiongpro** [comment]
> I already solve the problem and it's because that my Pytorch verison is 1.50.

I have the same problem and I have changed pytorch to version 1.5 ,but it does not work.

**Comment by Saumya-Shah** [comment]
I had the same problem. 
Just replace AT_CHECK and THCState_getCurrentStream(state) with TORCH_CHECK and at::cuda::getCurrentCUDAStream(), respectively and it works. 

https://github.com/hyangwinter/flownet3d_pytorch/issues/8#issuecomment-663925414

**Comment by brucetend** [comment]
> I had the same problem.
> Just replace AT_CHECK and THCState_getCurrentStream(state) with TORCH_CHECK and at::cuda::getCurrentCUDAStream(), respectively and it works.
> 
> [hyangwinter/flownet3d_pytorch#8 (comment)](https://github.com/hyangwinter/flownet3d_pytorch/issues/8#issuecomment-663925414)

Thank you, but it doesnot work for me, which version for Pytorch do you use?

**Comment by Saumya-Shah** [comment]
> > I had the same problem.
> > Just replace AT_CHECK and THCState_getCurrentStream(state) with TORCH_CHECK and at::cuda::getCurrentCUDAStream(), respectively and it works.
> > [hyangwinter/flownet3d_pytorch#8 (comment)](https://github.com/hyangwinter/flownet3d_pytorch/issues/8#issuecomment-663925414)
> 
> Thank you, but it doesnot work for me, which version for Pytorch do you use?

I had used Pytorch 1.5 with cuda 10.2.

**Comment by brucetend** [comment]
Thank you, dude! But I have another problem after that. like error: command ':/usr/local/cuda-10.1/bin/nvcc' failed with exit status 1

**Comment by Saumya-Shah** [comment]
That's probably a common cuda error. See if [this](https://www.programmersought.com/article/8191430209/) solves your problem.

**Comment by natsume7** [comment]
https://github.com/hyangwinter/flownet3d_pytorch/issues/8 has solved my problem,try

**Comment by Qifengle2020** [comment]
I have the same problem and my cuda 10.2 pytorch 1.5. I also replace AT_CHECK and THCState_getCurrentStream(state) with TORCH_CHECK and at::cuda::getCurrentCUDAStream(),But it doesn't work for me . Who can help me
