### ISSUE TITLE
eval.py problem

### ISSUE THREAD

**Issue by jczzp** [sshaoshuai/PointRCNN#201]
Traceback (most recent call last):
  File "eval_rcnn.py", line 899, in <module>
    eval_single_ckpt(root_result_dir)
  File "eval_rcnn.py", line 762, in eval_single_ckpt
    eval_one_epoch(model, test_loader, epoch_id, root_result_dir, logger)
  File "eval_rcnn.py", line 689, in eval_one_epoch
    ret_dict = eval_one_epoch_joint(model, dataloader, epoch_id, result_dir, logger)
  File "eval_rcnn.py", line 675, in eval_one_epoch_joint
    current_class=name_to_class[cfg.CLASSES])
  File "/home/jack/zzprcnnv2/tools/../tools/kitti_object_eval_python/evaluate.py", line 28, in evaluate
    return get_official_eval_result(gt_annos, dt_annos, current_class)
  File "/home/jack/zzprcnnv2/tools/../tools/kitti_object_eval_python/eval.py", line 643, in get_official_eval_result
    gt_annos, dt_annos, current_classes, min_overlaps, compute_aos)
  File "/home/jack/zzprcnnv2/tools/../tools/kitti_object_eval_python/eval.py", line 575, in do_eval
    min_overlaps, compute_aos)
  File "/home/jack/zzprcnnv2/tools/../tools/kitti_object_eval_python/eval.py", line 468, in eval_class
    rets = calculate_iou_partly(dt_annos, gt_annos, metric, num_parts)
  File "/home/jack/zzprcnnv2/tools/../tools/kitti_object_eval_python/eval.py", line 356, in calculate_iou_partly
    gt_boxes = np.concatenate([a["bbox"] for a in gt_annos_part], 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

**Comment by morpheus521** [comment]
I am having the same issue. Did you manage to resolve it?
