### ISSUE TITLE
No module named 'pointnet2_cuda'

### ISSUE THREAD

**Issue by hxb123622** [sshaoshuai/PointRCNN#211]
在运行readme Trained model中最后一行的代码“bash run_eval_model.sh”的时候发生了以下错误：
(myconda) root@6a05092648e6:/mnt/EPNet-master/tools# bash run_eval_model.sh
Traceback (most recent call last):
  File "eval_rcnn.py", line 7, in <module>
    from lib.net.point_rcnn import PointRCNN
  File "/mnt/EPNet-master/tools/../lib/net/point_rcnn.py", line 3, in <module>
    from lib.net.rpn import RPN
  File "/mnt/EPNet-master/tools/../lib/net/rpn.py", line 9, in <module>
    from pointnet2_msg import Pointnet2MSG
  File "/mnt/EPNet-master/tools/../lib/net/pointnet2_msg.py", line 4, in <module>
    from pointnet2_lib.pointnet2.pointnet2_modules import PointnetFPModule, PointnetSAModuleMSG
  File "/mnt/EPNet-master/tools/../pointnet2_lib/pointnet2/pointnet2_modules.py", line 5, in <module>
    from . import pointnet2_utils
  File "/mnt/EPNet-master/tools/../pointnet2_lib/pointnet2/pointnet2_utils.py", line 7, in <module>
    import pointnet2_cuda as pointnet2
ModuleNotFoundError: No module named 'pointnet2_cuda'

我猜测这是因为EPNet-master/pointnet2_lib/pointnet2文件夹下缺少了pointnet2_cuda.py文件的缘故。通过同文件夹下的setup.py似乎可以生成对应的文件，但是具体如何使用这个setup.py文件我还不是很清楚，请问谁可以帮忙看看吗？

**Comment by JianrongYan** [comment]
may be the gcc version dismatching, or nvcc version is different from torch.cuda version
