### ISSUE TITLE
eval_rcnn.py problem ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by leige521** [sshaoshuai/PointRCNN#226]
Traceback (most recent call last):
  File "eval_rcnn.py", line 902, in <module>
    eval_single_ckpt(root_result_dir)
  File "eval_rcnn.py", line 765, in eval_single_ckpt
    eval_one_epoch(model, test_loader, epoch_id, root_result_dir, logger)
  File "eval_rcnn.py", line 692, in eval_one_epoch
    ret_dict = eval_one_epoch_joint(model, dataloader, epoch_id, result_dir, logger)
  File "eval_rcnn.py", line 495, in eval_one_epoch_joint
    ret_dict = model(input_data)
  File "/home/liyuze/miniconda3/envs/epnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/liyuze/Code/PointRCNN-master/tools/../lib/net/point_rcnn.py", line 33, in forward
    rpn_output = self.rpn(input_data)
  File "/home/liyuze/miniconda3/envs/epnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/liyuze/Code/PointRCNN-master/tools/../lib/net/rpn.py", line 74, in forward
    backbone_xyz, backbone_features = self.backbone_net(pts_input)  # (B, N, 3), (B, C, N)
  File "/home/liyuze/miniconda3/envs/epnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/liyuze/Code/PointRCNN-master/tools/../lib/net/pointnet2_msg.py", line 61, in forward
    li_xyz, li_features = self.SA_modules[i](l_xyz[i], l_features[i])
ValueError: too many values to unpack (expected 2)

**Comment by leige521** [comment]
The problem occurs when I run python eval_rcnn.py --cfg_file cfgs/default.yaml --ckpt PointRCNN.pth --batch_size 1 --eval_mode rcnn --set RPN.LOC_XZ_FINE False code

**Comment by leige521** [comment]
我已经解决
