### ISSUE TITLE
FileNotFoundError:/tools/train_utils/train_utils.py

### ISSUE THREAD

**Issue by zjx99** [sshaoshuai/PointRCNN#24]
Hi,  Shaoshuai,
I got a problem when I tried to run the command in quick demo part to evaluate the pretrained model:

_**Traceback (most recent call last):
  File "eval_rcnn.py", line 902, in <module>
    eval_single_ckpt(root_result_dir)
  File "eval_rcnn.py", line 762, in eval_single_ckpt
    load_ckpt_based_on_args(model, logger)
  File "eval_rcnn.py", line 719, in load_ckpt_based_on_args
    train_utils.load_checkpoint(model, filename=args.ckpt, logger=logger)
  File "/home/b70379409/PointRCNN/tools/../tools/train_utils/train_utils.py", line 90, in load_checkpoint
    raise FileNotFoundError
FileNotFoundError**_

I ran the code in the folder tools.
Can you give me any clues? Thank you very much.
Jiaxing

**Comment by sshaoshuai** [comment]
It seems you specify a wrong ckpt path, please download the pretrained model and use `--ckpt model_path` to specify the path of your downloaded model.

**Comment by zjx99** [comment]
Hi, shaoshuai,
Thanks for your reply.
I put the downloaded model in PointRCNN folder, and I specified the path by the following command:
python3.7 eval_rcnn.py --cfg_file cfgs/default.yaml --ckpt ../PointRCNN.pth --batch_size 1 --eval_mode rcnn --set RPN.LOC_XZ_FINE False

But here comes assertion error: 
eval:   0%|                                                                                                                                                                        | 0/3769 [00:00<?, ?it/s]Traceback (most recent call last):
  File "eval_rcnn.py", line 902, in <module>
    eval_single_ckpt(root_result_dir)
  File "eval_rcnn.py", line 765, in eval_single_ckpt
    eval_one_epoch(model, test_loader, epoch_id, root_result_dir, logger)
  File "eval_rcnn.py", line 692, in eval_one_epoch
    ret_dict = eval_one_epoch_joint(model, dataloader, epoch_id, result_dir, logger)
  File "eval_rcnn.py", line 486, in eval_one_epoch_joint
    for data in dataloader:
  File "/home/anaconda3/envs/pointRCNN/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/anaconda3/envs/pointRCNN/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AssertionError: Traceback (most recent call last):
  File "/home/anaconda3/envs/pointRCNN/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/anaconda3/envs/pointRCNN/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/b70379409/PointRCNN/tools/../lib/datasets/kitti_rcnn_dataset.py", line 234, in __getitem__
    return self.get_rpn_sample(index)
  File "/home/b70379409/PointRCNN/tools/../lib/datasets/kitti_rcnn_dataset.py", line 249, in get_rpn_sample
    calib = self.get_calib(sample_id)
  File "/home/b70379409/PointRCNN/tools/../lib/datasets/kitti_rcnn_dataset.py", line 133, in get_calib
    return super().get_calib(idx % 10000)
  File "/home/b70379409/PointRCNN/tools/../lib/datasets/kitti_dataset.py", line 47, in get_calib
    assert os.path.exists(calib_file)
AssertionError

Later, I put the model into tools folder, the same error occured. Did I specify the model path in the right way or not? Do you know the reason for the error? 

Looking for your reply. 
Thank you very much.

**Comment by zjx99** [comment]
Also, I tried to evaluate a single checkpoint using the following command:
python eval_rcnn.py --cfg_file cfgs/default.yaml --ckpt ../output/rpn/ckpt/checkpoint_epoch_200.pth --batch_size 4 --eval_mode rcnn 
However, the same error occured saying that train_utils.py can't be found:

2019-05-01 22:54:43,183   INFO  cfg.TEST.SPLIT: val
2019-05-01 22:54:43,183   INFO  cfg.TEST.RPN_PRE_NMS_TOP_N: 9000
2019-05-01 22:54:43,183   INFO  cfg.TEST.RPN_POST_NMS_TOP_N: 100
2019-05-01 22:54:43,183   INFO  cfg.TEST.RPN_NMS_THRESH: 0.8
2019-05-01 22:54:43,183   INFO  cfg.TEST.RPN_DISTANCE_BASED_PROPOSE: True
2019-05-01 22:54:43,184   INFO  Load testing samples from ../data/KITTI/object/training
2019-05-01 22:54:43,184   INFO  Done: total test samples 3769
Traceback (most recent call last):
  File "eval_rcnn.py", line 902, in <module>
    eval_single_ckpt(root_result_dir)
  File "eval_rcnn.py", line 762, in eval_single_ckpt
    load_ckpt_based_on_args(model, logger)
  File "eval_rcnn.py", line 719, in load_ckpt_based_on_args
    train_utils.load_checkpoint(model, filename=args.ckpt, logger=logger)
  File "/home/b70379409/PointRCNN/tools/../tools/train_utils/train_utils.py", line 90, in load_checkpoint
    raise FileNotFoundError
FileNotFoundError

What is this checkpoint_epoch_200.pth file? Should it be downloaded somewhere or will it be supposed to generate during the checking process?

I'd be very appreciated if you can give me any help.  Thanks!

Jiaxing

**Comment by sshaoshuai** [comment]
You should download the pretrained model from the link I provided in the readme, and use `--ckpt` to specify the path of your downloaded file, and then run this command with the updated `--ckpt`.

**Comment by zjx99** [comment]
Thank you, I did so. But here came an assertion error, just as the outcome when I put the model inside of tools folder:
_2019-05-07 21:12:32,390   INFO  ==> Loading from checkpoint '/home/b70379409/Downloads/PointRCNN.pth'
2019-05-07 21:12:32,430   INFO  ==> Done
2019-05-07 21:12:32,431   INFO  ---- EPOCH 70379409 JOINT EVALUATION ----
2019-05-07 21:12:32,431   INFO  ==> Output file: ../output/rcnn/default/eval/epoch_70379409/val
eval:   0%|                                                                                                                                                                        | 0/3769 [00:00<?, ?it/s]Traceback (most recent call last):
  File "eval_rcnn.py", line 902, in <module>
    eval_single_ckpt(root_result_dir)
  File "eval_rcnn.py", line 765, in eval_single_ckpt
    eval_one_epoch(model, test_loader, epoch_id, root_result_dir, logger)
  File "eval_rcnn.py", line 692, in eval_one_epoch
    ret_dict = eval_one_epoch_joint(model, dataloader, epoch_id, result_dir, logger)
  File "eval_rcnn.py", line 486, in eval_one_epoch_joint
    for data in dataloader:
  File "/home/anaconda3/envs/pointRCNN/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/anaconda3/envs/pointRCNN/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AssertionError: Traceback (most recent call last):
  File "/home/anaconda3/envs/pointRCNN/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/anaconda3/envs/pointRCNN/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/b70379409/PointRCNN/tools/../lib/datasets/kitti_rcnn_dataset.py", line 234, in __getitem__
    return self.get_rpn_sample(index)
  File "/home/b70379409/PointRCNN/tools/../lib/datasets/kitti_rcnn_dataset.py", line 249, in get_rpn_sample
    calib = self.get_calib(sample_id)
  File "/home/b70379409/PointRCNN/tools/../lib/datasets/kitti_rcnn_dataset.py", line 133, in get_calib
    return super().get_calib(idx % 10000)
  File "/home/b70379409/PointRCNN/tools/../lib/datasets/kitti_dataset.py", line 47, in get_calib
    assert os.path.exists(calib_file)
AssertionError_

So, what's the reason for this error?
Thanks

**Comment by 1992Zz** [comment]
you should download pre-model and add to configuration of command Line.
