### ISSUE TITLE
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:441

### ISSUE THREAD

**Issue by qinhuaping** [sshaoshuai/PointRCNN#42]

**Comment by wghvip** [comment]
你好，我遇到了同样的问题，请问你是怎么解决的

**Comment by zbp-xxxp** [comment]
我也遇到了这样的问题，想问一下有解决办法吗？
```
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=405 error=11 : invalid argument
Traceback (most recent call last):
  File "eval_rcnn.py", line 902, in <module>
    eval_single_ckpt(root_result_dir)
  File "eval_rcnn.py", line 765, in eval_single_ckpt
    eval_one_epoch(model, test_loader, epoch_id, root_result_dir, logger)
  File "eval_rcnn.py", line 692, in eval_one_epoch
    ret_dict = eval_one_epoch_joint(model, dataloader, epoch_id, result_dir, logger)
  File "eval_rcnn.py", line 495, in eval_one_epoch_joint
    ret_dict = model(input_data)
  File "/home/lnn/anaconda3/envs/pointrcnn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lnn/zbp/PointRCNN/tools/../lib/net/point_rcnn.py", line 62, in forward
    rcnn_output = self.rcnn_net(rcnn_input_info)
  File "/home/lnn/anaconda3/envs/pointrcnn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lnn/zbp/PointRCNN/tools/../lib/net/rcnn_net.py", line 152, in forward
    batch_rois[k, :, 6])
  File "/home/lnn/zbp/PointRCNN/tools/../lib/utils/kitti_utils.py", line 61, in rotate_pc_along_y_torch
    pc[:, :, [0, 2]] = torch.matmul(pc_temp, R.permute(0, 2, 1))  # (N, 512, 2)
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:441
eval:   0%|                                                          | 0/943 [00:00<?, ?it/s]
```
