### ISSUE TITLE
solution for this issue please provide

### ISSUE THREAD

**Issue by divyashu** [sshaoshuai/PointRCNN#51]
(pt) divya@divya-pc:~/virtual/pt/PointRCNN/tools$ python3 eval_rcnn.py --cfg_file cfgs/default.yaml --ckpt PointRCNN.pth --batch_size 1 --eval_mode rcnn --set RPN.LOC_XZ_FINE False
/home/divya/virtual/pt/PointRCNN/tools/../lib/config.py:187: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yaml_cfg = edict(yaml.load(f))
2019-05-28 15:28:03,034   INFO  **********************Start logging**********************
2019-05-28 15:28:03,034   INFO  cfg_file         cfgs/default.yaml
2019-05-28 15:28:03,034   INFO  eval_mode        rcnn
2019-05-28 15:28:03,034   INFO  eval_all         False
2019-05-28 15:28:03,035   INFO  test             False
2019-05-28 15:28:03,035   INFO  ckpt             PointRCNN.pth
2019-05-28 15:28:03,035   INFO  rpn_ckpt         None
2019-05-28 15:28:03,035   INFO  rcnn_ckpt        None
2019-05-28 15:28:03,035   INFO  batch_size       1
2019-05-28 15:28:03,035   INFO  workers          4
2019-05-28 15:28:03,035   INFO  extra_tag        default
2019-05-28 15:28:03,035   INFO  output_dir       None
2019-05-28 15:28:03,035   INFO  ckpt_dir         None
2019-05-28 15:28:03,035   INFO  save_result      False
2019-05-28 15:28:03,035   INFO  save_rpn_feature False
2019-05-28 15:28:03,035   INFO  random_select    True
2019-05-28 15:28:03,035   INFO  start_epoch      0
2019-05-28 15:28:03,035   INFO  rcnn_eval_roi_dir None
2019-05-28 15:28:03,035   INFO  rcnn_eval_feature_dir None
2019-05-28 15:28:03,035   INFO  set_cfgs         ['RPN.LOC_XZ_FINE', 'False']
2019-05-28 15:28:03,035   INFO  cfg.TAG: default
2019-05-28 15:28:03,035   INFO  cfg.CLASSES: Car
2019-05-28 15:28:03,035   INFO  cfg.INCLUDE_SIMILAR_TYPE: True
2019-05-28 15:28:03,035   INFO  cfg.AUG_DATA: True
2019-05-28 15:28:03,035   INFO  cfg.AUG_METHOD_LIST: ['rotation', 'scaling', 'flip']
2019-05-28 15:28:03,035   INFO  cfg.AUG_METHOD_PROB: [1.0, 1.0, 0.5]
2019-05-28 15:28:03,035   INFO  cfg.AUG_ROT_RANGE: 18
2019-05-28 15:28:03,035   INFO  cfg.GT_AUG_ENABLED: True
2019-05-28 15:28:03,035   INFO  cfg.GT_EXTRA_NUM: 15
2019-05-28 15:28:03,036   INFO  cfg.GT_AUG_RAND_NUM: True
2019-05-28 15:28:03,036   INFO  cfg.GT_AUG_APPLY_PROB: 1.0
2019-05-28 15:28:03,036   INFO  cfg.GT_AUG_HARD_RATIO: 0.6
2019-05-28 15:28:03,036   INFO  cfg.PC_REDUCE_BY_RANGE: True
2019-05-28 15:28:03,036   INFO  cfg.PC_AREA_SCOPE: [[-40.   40. ]
 [ -1.    3. ]
 [  0.   70.4]]
2019-05-28 15:28:03,036   INFO  cfg.CLS_MEAN_SIZE: [[1.5256319 1.6285675 3.8831165]]
2019-05-28 15:28:03,036   INFO  
cfg.RPN = edict()
2019-05-28 15:28:03,036   INFO  cfg.RPN.ENABLED: True
2019-05-28 15:28:03,036   INFO  cfg.RPN.FIXED: True
2019-05-28 15:28:03,036   INFO  cfg.RPN.USE_INTENSITY: False
2019-05-28 15:28:03,036   INFO  cfg.RPN.LOC_XZ_FINE: False
2019-05-28 15:28:03,036   INFO  cfg.RPN.LOC_SCOPE: 3.0
2019-05-28 15:28:03,036   INFO  cfg.RPN.LOC_BIN_SIZE: 0.5
2019-05-28 15:28:03,036   INFO  cfg.RPN.NUM_HEAD_BIN: 12
2019-05-28 15:28:03,036   INFO  cfg.RPN.BACKBONE: pointnet2_msg
2019-05-28 15:28:03,036   INFO  cfg.RPN.USE_BN: True
2019-05-28 15:28:03,036   INFO  cfg.RPN.NUM_POINTS: 16384
2019-05-28 15:28:03,036   INFO  
cfg.RPN.SA_CONFIG = edict()
2019-05-28 15:28:03,036   INFO  cfg.RPN.SA_CONFIG.NPOINTS: [4096, 1024, 256, 64]
2019-05-28 15:28:03,037   INFO  cfg.RPN.SA_CONFIG.RADIUS: [[0.1, 0.5], [0.5, 1.0], [1.0, 2.0], [2.0, 4.0]]
2019-05-28 15:28:03,037   INFO  cfg.RPN.SA_CONFIG.NSAMPLE: [[16, 32], [16, 32], [16, 32], [16, 32]]
2019-05-28 15:28:03,037   INFO  cfg.RPN.SA_CONFIG.MLPS: [[[16, 16, 32], [32, 32, 64]], [[64, 64, 128], [64, 96, 128]], [[128, 196, 256], [128, 196, 256]], [[256, 256, 512], [256, 384, 512]]]
2019-05-28 15:28:03,037   INFO  cfg.RPN.FP_MLPS: [[128, 128], [256, 256], [512, 512], [512, 512]]
2019-05-28 15:28:03,037   INFO  cfg.RPN.CLS_FC: [128]
2019-05-28 15:28:03,037   INFO  cfg.RPN.REG_FC: [128]
2019-05-28 15:28:03,037   INFO  cfg.RPN.DP_RATIO: 0.5
2019-05-28 15:28:03,037   INFO  cfg.RPN.LOSS_CLS: SigmoidFocalLoss
2019-05-28 15:28:03,037   INFO  cfg.RPN.FG_WEIGHT: 15
2019-05-28 15:28:03,037   INFO  cfg.RPN.FOCAL_ALPHA: [0.25, 0.75]
2019-05-28 15:28:03,037   INFO  cfg.RPN.FOCAL_GAMMA: 2.0
2019-05-28 15:28:03,037   INFO  cfg.RPN.REG_LOSS_WEIGHT: [1.0, 1.0, 1.0, 1.0]
2019-05-28 15:28:03,037   INFO  cfg.RPN.LOSS_WEIGHT: [1.0, 1.0]
2019-05-28 15:28:03,037   INFO  cfg.RPN.NMS_TYPE: normal
2019-05-28 15:28:03,037   INFO  cfg.RPN.SCORE_THRESH: 0.3
2019-05-28 15:28:03,037   INFO  
cfg.RCNN = edict()
2019-05-28 15:28:03,037   INFO  cfg.RCNN.ENABLED: True
2019-05-28 15:28:03,037   INFO  cfg.RCNN.USE_RPN_FEATURES: True
2019-05-28 15:28:03,037   INFO  cfg.RCNN.USE_MASK: True
2019-05-28 15:28:03,037   INFO  cfg.RCNN.MASK_TYPE: seg
2019-05-28 15:28:03,037   INFO  cfg.RCNN.USE_INTENSITY: False
2019-05-28 15:28:03,037   INFO  cfg.RCNN.USE_DEPTH: True
2019-05-28 15:28:03,037   INFO  cfg.RCNN.USE_SEG_SCORE: False
2019-05-28 15:28:03,037   INFO  cfg.RCNN.ROI_SAMPLE_JIT: True
2019-05-28 15:28:03,037   INFO  cfg.RCNN.ROI_FG_AUG_TIMES: 10
2019-05-28 15:28:03,037   INFO  cfg.RCNN.REG_AUG_METHOD: multiple
2019-05-28 15:28:03,037   INFO  cfg.RCNN.POOL_EXTRA_WIDTH: 1.0
2019-05-28 15:28:03,037   INFO  cfg.RCNN.LOC_SCOPE: 1.5
2019-05-28 15:28:03,037   INFO  cfg.RCNN.LOC_BIN_SIZE: 0.5
2019-05-28 15:28:03,038   INFO  cfg.RCNN.NUM_HEAD_BIN: 9
2019-05-28 15:28:03,038   INFO  cfg.RCNN.LOC_Y_BY_BIN: False
2019-05-28 15:28:03,038   INFO  cfg.RCNN.LOC_Y_SCOPE: 0.5
2019-05-28 15:28:03,038   INFO  cfg.RCNN.LOC_Y_BIN_SIZE: 0.25
2019-05-28 15:28:03,038   INFO  cfg.RCNN.SIZE_RES_ON_ROI: False
2019-05-28 15:28:03,038   INFO  cfg.RCNN.USE_BN: False
2019-05-28 15:28:03,038   INFO  cfg.RCNN.DP_RATIO: 0.0
2019-05-28 15:28:03,038   INFO  cfg.RCNN.BACKBONE: pointnet
2019-05-28 15:28:03,038   INFO  cfg.RCNN.XYZ_UP_LAYER: [128, 128]
2019-05-28 15:28:03,038   INFO  cfg.RCNN.NUM_POINTS: 512
2019-05-28 15:28:03,038   INFO  
cfg.RCNN.SA_CONFIG = edict()
2019-05-28 15:28:03,038   INFO  cfg.RCNN.SA_CONFIG.NPOINTS: [128, 32, -1]
2019-05-28 15:28:03,038   INFO  cfg.RCNN.SA_CONFIG.RADIUS: [0.2, 0.4, 100]
2019-05-28 15:28:03,038   INFO  cfg.RCNN.SA_CONFIG.NSAMPLE: [64, 64, 64]
2019-05-28 15:28:03,038   INFO  cfg.RCNN.SA_CONFIG.MLPS: [[128, 128, 128], [128, 128, 256], [256, 256, 512]]
2019-05-28 15:28:03,038   INFO  cfg.RCNN.CLS_FC: [256, 256]
2019-05-28 15:28:03,038   INFO  cfg.RCNN.REG_FC: [256, 256]
2019-05-28 15:28:03,038   INFO  cfg.RCNN.LOSS_CLS: BinaryCrossEntropy
2019-05-28 15:28:03,038   INFO  cfg.RCNN.FOCAL_ALPHA: [0.25, 0.75]
2019-05-28 15:28:03,038   INFO  cfg.RCNN.FOCAL_GAMMA: 2.0
2019-05-28 15:28:03,038   INFO  cfg.RCNN.CLS_WEIGHT: [1. 1. 1.]
2019-05-28 15:28:03,038   INFO  cfg.RCNN.CLS_FG_THRESH: 0.6
2019-05-28 15:28:03,038   INFO  cfg.RCNN.CLS_BG_THRESH: 0.45
2019-05-28 15:28:03,038   INFO  cfg.RCNN.CLS_BG_THRESH_LO: 0.05
2019-05-28 15:28:03,039   INFO  cfg.RCNN.REG_FG_THRESH: 0.55
2019-05-28 15:28:03,039   INFO  cfg.RCNN.FG_RATIO: 0.5
2019-05-28 15:28:03,039   INFO  cfg.RCNN.ROI_PER_IMAGE: 64
2019-05-28 15:28:03,039   INFO  cfg.RCNN.HARD_BG_RATIO: 0.8
2019-05-28 15:28:03,039   INFO  cfg.RCNN.SCORE_THRESH: 0.3
2019-05-28 15:28:03,039   INFO  cfg.RCNN.NMS_THRESH: 0.1
2019-05-28 15:28:03,039   INFO  
cfg.TRAIN = edict()
2019-05-28 15:28:03,039   INFO  cfg.TRAIN.SPLIT: train
2019-05-28 15:28:03,039   INFO  cfg.TRAIN.VAL_SPLIT: smallval
2019-05-28 15:28:03,039   INFO  cfg.TRAIN.LR: 0.002
2019-05-28 15:28:03,039   INFO  cfg.TRAIN.LR_CLIP: 1e-05
2019-05-28 15:28:03,039   INFO  cfg.TRAIN.LR_DECAY: 0.5
2019-05-28 15:28:03,039   INFO  cfg.TRAIN.DECAY_STEP_LIST: [100, 150, 180, 200]
2019-05-28 15:28:03,039   INFO  cfg.TRAIN.LR_WARMUP: True
2019-05-28 15:28:03,039   INFO  cfg.TRAIN.WARMUP_MIN: 0.0002
2019-05-28 15:28:03,039   INFO  cfg.TRAIN.WARMUP_EPOCH: 1
2019-05-28 15:28:03,039   INFO  cfg.TRAIN.BN_MOMENTUM: 0.1
2019-05-28 15:28:03,039   INFO  cfg.TRAIN.BN_DECAY: 0.5
2019-05-28 15:28:03,039   INFO  cfg.TRAIN.BNM_CLIP: 0.01
2019-05-28 15:28:03,039   INFO  cfg.TRAIN.BN_DECAY_STEP_LIST: [1000]
2019-05-28 15:28:03,039   INFO  cfg.TRAIN.OPTIMIZER: adam_onecycle
2019-05-28 15:28:03,039   INFO  cfg.TRAIN.WEIGHT_DECAY: 0.001
2019-05-28 15:28:03,039   INFO  cfg.TRAIN.MOMENTUM: 0.9
2019-05-28 15:28:03,039   INFO  cfg.TRAIN.MOMS: [0.95, 0.85]
2019-05-28 15:28:03,039   INFO  cfg.TRAIN.DIV_FACTOR: 10.0
2019-05-28 15:28:03,039   INFO  cfg.TRAIN.PCT_START: 0.4
2019-05-28 15:28:03,039   INFO  cfg.TRAIN.GRAD_NORM_CLIP: 1.0
2019-05-28 15:28:03,039   INFO  cfg.TRAIN.RPN_PRE_NMS_TOP_N: 9000
2019-05-28 15:28:03,039   INFO  cfg.TRAIN.RPN_POST_NMS_TOP_N: 512
2019-05-28 15:28:03,040   INFO  cfg.TRAIN.RPN_NMS_THRESH: 0.85
2019-05-28 15:28:03,040   INFO  cfg.TRAIN.RPN_DISTANCE_BASED_PROPOSE: True
2019-05-28 15:28:03,040   INFO  
cfg.TEST = edict()
2019-05-28 15:28:03,040   INFO  cfg.TEST.SPLIT: val
2019-05-28 15:28:03,040   INFO  cfg.TEST.RPN_PRE_NMS_TOP_N: 9000
2019-05-28 15:28:03,040   INFO  cfg.TEST.RPN_POST_NMS_TOP_N: 100
2019-05-28 15:28:03,040   INFO  cfg.TEST.RPN_NMS_THRESH: 0.8
2019-05-28 15:28:03,040   INFO  cfg.TEST.RPN_DISTANCE_BASED_PROPOSE: True
2019-05-28 15:28:03,041   INFO  Load testing samples from ../data/KITTI/object/training
2019-05-28 15:28:03,041   INFO  Done: total test samples 3769
2019-05-28 15:28:05,774   INFO  ==> Loading from checkpoint 'PointRCNN.pth'
2019-05-28 15:28:05,802   INFO  ==> Done
2019-05-28 15:28:05,803   INFO  ---- EPOCH no_number JOINT EVALUATION ----
2019-05-28 15:28:05,803   INFO  ==> Output file: ../output/rcnn/default/eval/epoch_no_number/val
eval:   0%|▏                                                             | 11/3769 [00:12<1:05:31,  1.05s/it, mode=EVAL, recall=20/25]Traceback (most recent call last):
  File "eval_rcnn.py", line 902, in <module>
    eval_single_ckpt(root_result_dir)
  File "eval_rcnn.py", line 765, in eval_single_ckpt
    eval_one_epoch(model, test_loader, epoch_id, root_result_dir, logger)
  File "eval_rcnn.py", line 692, in eval_one_epoch
    ret_dict = eval_one_epoch_joint(model, dataloader, epoch_id, result_dir, logger)
  File "eval_rcnn.py", line 486, in eval_one_epoch_joint
    for data in dataloader:
  File "/home/divya/virtual/pt/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/divya/virtual/pt/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AssertionError: Traceback (most recent call last):
  File "/home/divya/virtual/pt/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/divya/virtual/pt/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/divya/virtual/pt/PointRCNN/tools/../lib/datasets/kitti_rcnn_dataset.py", line 234, in __getitem__
    return self.get_rpn_sample(index)
  File "/home/divya/virtual/pt/PointRCNN/tools/../lib/datasets/kitti_rcnn_dataset.py", line 251, in get_rpn_sample
    img_shape = self.get_image_shape(sample_id)
  File "/home/divya/virtual/pt/PointRCNN/tools/../lib/datasets/kitti_rcnn_dataset.py", line 130, in get_image_shape
    return super().get_image_shape(idx % 10000)
  File "/home/divya/virtual/pt/PointRCNN/tools/../lib/datasets/kitti_dataset.py", line 35, in get_image_shape
    assert os.path.exists(img_file)
AssertionError

**Comment by wolf943134497** [comment]
hi  @divyashu    problem  solved?    how to slove this issue?  Thanks

**Comment by Collapsarva** [comment]
I have also encountered this problem. Have you resolved it?
