### ISSUE TITLE
The performance of Pretrained model  on KITTI test set

### ISSUE THREAD

**Issue by lwjtyzh** [sshaoshuai/PointRCNN#56]
Thanks for your paper and code! I noticed that you have evaluated the pretrained model provided in README on KITTI test set ,and there are 2 test results on the KITTI Benchmark.Is it one of the two results?If not, could you please share the result of evaluating the pretrained model on KITTI test split? Thank you again.

**Comment by sshaoshuai** [comment]
Yes, the released model is the model shown on the KITTI test benchmark. And you could generate the test results by setting `TEST.SPLIT` as test split. Also, please do not published the test results if you use my released model to submit to the test server since it will confuse the KITTI test board.

**Comment by lwjtyzh** [comment]
OK, thanks!

**Comment by zjx99** [comment]
@sshaoshuai 
I used the following command to evaluate the pretrained model on the test split of KITTI
**_python3.7 eval_rcnn.py --cfg_file cfgs/default.yaml --ckpt PointRCNN.pth --batch_size 1 --eval_mode rcnn --test --set TEST.SPLIT test --set RPN.LOC_XZ_FINE False_**

However, I got the following errors:
**_Traceback (most recent call last):
  File "eval_rcnn.py", line 867, in <module>
    cfg_from_list(args.set_cfgs)
  File "/home/b70379409/PointRCNN/tools/../lib/config.py", line 225, in cfg_from_list
    assert len(cfg_list) % 2 == 0
AssertionError_**

Could you give me any clue about this issue?  Thank you very much!

**Comment by chenxyyy** [comment]
@zjx99 
I met the same problem.
Do you kbow how to fix it?

**Comment by lanshiyinging** [comment]
> @sshaoshuai
> I used the following command to evaluate the pretrained model on the test split of KITTI
> **_python3.7 eval_rcnn.py --cfg_file cfgs/default.yaml --ckpt PointRCNN.pth --batch_size 1 --eval_mode rcnn --test --set TEST.SPLIT test --set RPN.LOC_XZ_FINE False_**
> 
> However, I got the following errors:
> **_Traceback (most recent call last): File "eval_rcnn.py", line 867, in cfg_from_list(args.set_cfgs) File "/home/b70379409/PointRCNN/tools/../lib/config.py", line 225, in cfg_from_list assert len(cfg_list) % 2 == 0 AssertionError_**
> 
> Could you give me any clue about this issue? Thank you very much!

just need one --set, like:
python3.7 eval_rcnn.py --cfg_file cfgs/default.yaml --ckpt PointRCNN.pth --batch_size 1 --eval_mode rcnn --test --set TEST.SPLIT test RPN.LOC_XZ_FINE False

**Comment by greyweb** [comment]
Can we use eval_rcnn.py to generate the labels for a custom test data( with png, bin and calib files, which in the directories as mention and also having them updated on the test.txt file)?
