### ISSUE TITLE
can not import iou3d_cuda

### ISSUE THREAD

**Issue by sybilWsybil** [sshaoshuai/PointRCNN#57]
Traceback (most recent call last):
  File "eval_rcnn.py", line 7, in <module>
    from lib.net.point_rcnn import PointRCNN
  File "/export/work/CODE/pointnet_set/PointRCNN/tools/../lib/net/point_rcnn.py", line 3, in <module>
    from lib.net.rpn import RPN
  File "/export/work/CODE/pointnet_set/PointRCNN/tools/../lib/net/rpn.py", line 4, in <module>
    from lib.rpn.proposal_layer import ProposalLayer
  File "/export/work/CODE/pointnet_set/PointRCNN/tools/../lib/rpn/proposal_layer.py", line 6, in <module>
    import lib.utils.iou3d.iou3d_utils as iou3d_utils
  File "/export/work/CODE/pointnet_set/PointRCNN/tools/../lib/utils/iou3d/iou3d_utils.py", line 2, in <module>
    import iou3d_cuda
ImportError: /home/jdcn/anaconda3/envs/torch/lib/python3.6/site-packages/iou3d-0.0.0-py3.6-linux-x86_64.egg/iou3d_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

**Comment by sshaoshuai** [comment]
Please check your compiling log, maybe your gcc version is not enough (should be gcc-5.4+).

**Comment by Manojbhat09** [comment]
Hello ,

this is output I get 
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Still facing this issue

Please let me know which version of Anaconda, Python, pytorch, cuda, cudatoolkit, cudnn have you used

I create new python 3.6 conda env, 
then conda install pytorch torchvision cuda80 -c pytorch 
then while compiling it shows this issue

**Comment by Manojbhat09** [comment]
@sybilWsybil 
Hey I solved it by editing the torch cpp_extension.py

Refer to this: https://aur.archlinux.org/packages/python-apex-git/
Do the edit,
remove all build dist egg __pycache files from Pointnet, iou3d and roipooling folders
Then build again 
And evaluate.

Try it.

**Comment by sybilWsybil** [comment]
> Please check your compiling log, maybe your gcc version is not enough (should be gcc-5.4+).

my gcc version is 5.4.0

**Comment by sybilWsybil** [comment]
> @sybilWsybil
> Hey I solved it by editing the torch cpp_extension.py
> 
> Refer to this: https://aur.archlinux.org/packages/python-apex-git/
> Do the edit,
> remove all build dist egg __pycache files from Pointnet, iou3d and roipooling folders
> Then build again
> And evaluate.
> 
> Try it.

Is this a problem of pytorch's version? I don't want to change .py in pytorch,because my other may not run successfully

**Comment by XibinSong** [comment]
@sybilWsybil @sshaoshuai 

Hey, do you solve the problem now? I get the same problem and can not fix it (gcc 5.4.0 and  ubuntu 16.04).

Thanks.

**Comment by sybilWsybil** [comment]
> @sybilWsybil @sshaoshuai
> 
> Hey, do you solve the problem now? I get the same problem and can not fix it (gcc 5.4.0 and ubuntu 16.04).
> 
> Thanks.

I have not fix it

**Comment by jcmayoral** [comment]
H. I have the same issue today, I solved modifying the build_and_install.sh forcing it to use python3 (in my case python 3.5.2) instead of python (it could be also solved changing the default python version on Ubuntu for me that would not be a solution). After that, it indicates some issues with some strings in the eval.py, correcting that it works.

**Comment by gongshichina** [comment]
I sloved it by changing the setup.py under iou3d as below
Note: **If** `torch._C._GLIBCXX_USE_CXX11_ABI` is True, it indicates your pytorch is compiled with using `CXX11_ABI`, so change` '-D_GLIBCXX_USE_CXX11_ABI=0'` to `'-D_GLIBCXX_USE_CXX11_ABI=1'`
Furthermore, you must import torch before import iou3d_cuda

iou3d/setup.py
```
from setuptools import setup
from torch.utils.cpp_extension import BuildExtension, CUDAExtension

setup(
    name='iou3d',
    ext_modules=[
        CUDAExtension('iou3d_cuda', [
            'src/iou3d.cpp',
            'src/iou3d_kernel.cu',
        ],
        extra_compile_args=['-D_GLIBCXX_USE_CXX11_ABI=0', '-std=c++11',{'nvcc': ['-O2']}])],
    cmdclass={'build_ext': BuildExtension}) 
```
_reference_:[https://discuss.pytorch.org/t/cppextension-error-when-import-c/31962]

**Comment by gujiaqivadin** [comment]
> I sloved it by changing the setup.py under iou3d as below
> Note: **If** `torch._C._GLIBCXX_USE_CXX11_ABI` is True, it indicates your pytorch is compiled with using `CXX11_ABI`, so change` '-D_GLIBCXX_USE_CXX11_ABI=0'` to `'-D_GLIBCXX_USE_CXX11_ABI=1'`
> Furthermore, you must import torch before import iou3d_cuda
> 
> iou3d/setup.py
> 
> ```
> from setuptools import setup
> from torch.utils.cpp_extension import BuildExtension, CUDAExtension
> 
> setup(
>     name='iou3d',
>     ext_modules=[
>         CUDAExtension('iou3d_cuda', [
>             'src/iou3d.cpp',
>             'src/iou3d_kernel.cu',
>         ],
>         extra_compile_args=['-D_GLIBCXX_USE_CXX11_ABI=0', '-std=c++11',{'nvcc': ['-O2']}])],
>     cmdclass={'build_ext': BuildExtension}) 
> ```
> 
> _reference_:[1](https://discuss.pytorch.org/t/cppextension-error-when-import-c/31962)

Hello, I tried your method, but it didn't work. I don't know if it is because I already install a iou3d_cuda version before. And my gcc version is 4.8.4.

**Comment by qiaoli96** [comment]
额前的

**Comment by qiaoli96** [comment]
I ran into the same problem, python version 3.6.2, cuda is 10.0, pytorch is 1.0.1, cudatoolkit is 10.0.130, cudnn is 7.6.4, gcc version 5.4.0. Is there a problem with my version?

**Comment by qiaoli96** [comment]
thank you. I have spent serveral days to solve this problem.

**Comment by triangleCZH** [comment]
I use python3.7 with pytorch 1.1.0 and the bug is fixed. cheers

**Comment by jeffepok** [comment]
> @sybilWsybil Hey I solved it by editing the torch cpp_extension.py
> 
> Refer to this: https://aur.archlinux.org/packages/python-apex-git/ Do the edit, remove all build dist egg __pycache files from Pointnet, iou3d and roipooling folders Then build again And evaluate.
> 
> Try it.

Hi please how do I build again?

**Comment by MSunDYY** [comment]
After trying for a whole afternoon,I conclude that you must import torch before import iou3d_cuda!

**Comment by qiaoli96** [comment]
我已收到您的邮件，谢谢！--李悄（^_^）
