### ISSUE TITLE
AssertionError when running quick demo

### ISSUE THREAD

**Issue by gujiaqivadin** [sshaoshuai/PointRCNN#83]
Hello!
I came across a problem when running quick demo of PointRCNN. And I cannot figure out what the AssertionError means.

Here is my terminal shows:

/media/sdata/vadin/PointRCNN/tools/../lib/config.py:187: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yaml_cfg = edict(yaml.load(f))
Traceback (most recent call last):
  File "eval_rcnn.py", line 867, in <module>
    cfg_from_list(args.set_cfgs)
  File "/media/sdata/vadin/PointRCNN/tools/../lib/config.py", line 230, in cfg_from_list
    assert subkey in d
AssertionError

**Comment by bmankirLinker** [comment]
> Hello!
> I came across a problem when running quick demo of PointRCNN. And I cannot figure out what the AssertionError means.
> 
> Here is my terminal shows:
> 
> /media/sdata/vadin/PointRCNN/tools/../lib/config.py:187: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
> yaml_cfg = edict(yaml.load(f))
> Traceback (most recent call last):
> File "eval_rcnn.py", line 867, in 
> cfg_from_list(args.set_cfgs)
> File "/media/sdata/vadin/PointRCNN/tools/../lib/config.py", line 230, in cfg_from_list
> assert subkey in d
> AssertionError

What did you change in your config ` yaml ` file?
