### ISSUE TITLE
rcnn training stopped by error

### ISSUE THREAD

**Issue by candisjesus** [sshaoshuai/PointRCNN#97]
Hey, sorry to bother again!
Recently I am working on training Kitti dataset for RCNN. And it can be trained for a few batches, and then has error:
train:   7%|▋         | 121/1632 [02:24<24:54,  1.01it/s, total_it=120]
epochs:   0%|          | 0/70 [02:24<?, ?it/s, reg_fg_sum=43, loss=3.52, lr=0.0002]
train:   7%|▋         | 122/1632 [02:25<25:06,  1.00it/s, total_it=121]
epochs:   0%|          | 0/70 [02:25<?, ?it/s, reg_fg_sum=43, loss=3.24, lr=0.0002]
                                                                       
Traceback (most recent call last):
  File "D:/coding/PycharmProjects/PointRCNN/tools/train_rcnn.py", line 250, in <module>
    lr_scheduler_each_iter=(cfg.TRAIN.OPTIMIZER == 'adam_onecycle')
  File "D:\coding\PycharmProjects\PointRCNN\tools\..\tools\train_utils\train_utils.py", line 199, in train
    loss, tb_dict, disp_dict = self._train_it(batch)
  File "D:\coding\PycharmProjects\PointRCNN\tools\..\tools\train_utils\train_utils.py", line 132, in _train_it
    loss, tb_dict, disp_dict = self.model_fn(self.model, batch)
  File "D:\coding\PycharmProjects\PointRCNN\tools\..\lib\net\train_functions.py", line 36, in model_fn
    ret_dict = model(input_data)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\coding\PycharmProjects\PointRCNN\tools\..\lib\net\point_rcnn.py", line 62, in forward
    rcnn_output = self.rcnn_net(rcnn_input_info)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\coding\PycharmProjects\PointRCNN\tools\..\lib\net\rcnn_net.py", line 123, in forward
    target_dict = self.proposal_target_layer(input_data)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\coding\PycharmProjects\PointRCNN\tools\..\lib\rpn\proposal_target_layer.py", line 17, in forward
    batch_rois, batch_gt_of_rois, batch_roi_iou = self.sample_rois_for_rcnn(roi_boxes3d, gt_boxes3d)
  File "D:\coding\PycharmProjects\PointRCNN\tools\..\lib\rpn\proposal_target_layer.py", line 100, in sample_rois_for_rcnn
    while cur_gt[k].sum() == 0:
IndexError: index -3 is out of bounds for dimension 0 with size 2

Any idea for solving this problem? Thanks a lot

**Comment by Disfish9527** [comment]
If you train RCNN network with offline GT augmentation, the required disk size is about 300G. I think your situation is due to insufficient memory.

**Comment by candisjesus** [comment]
> If you train RCNN network with offline GT augmentation, the required disk size is about 300G. I think your situation is due to insufficient memory.

I used online GT augmentation, does it make any difference？

**Comment by saltoricristiano** [comment]
Hi @candisjesus, 
I'm having the same problem in the online training of RCNN. Have you solved it? If yes, how? It seems related to a check they do in proposal_target_layer.py to remove "zeroed" boxes.
Thank you in advance!

**Comment by saltoricristiano** [comment]
Hi, for the ones that are experiencing the same issue, in my case I solved... it was an issue in the loading of the labels.
Thank you!

**Comment by gehadza** [comment]
Please can you tell me how solve this problem @saltoricristiano  by labels?
